# -*- coding: utf-8 -*-
"""ProyectoFinalML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WzsXgrVo4kY13jN1OfaWhzWazDomnYek

# Detección de tráfico anómalo en dispositivos IoT mediante aprendizaje automático

Este notebook evalúa modelos de aprendizaje automático sobre el dataset N-BaIoT para detectar tráfico benigno y tráfico asociado a botnets en dispositivos IoT.

Modelos evaluados:

- K-Means multiclase
- K-Means binario
- Gaussian Naive Bayes
- Isolation Forest multiclase adaptado

También se generan matrices de confusión, métricas de rendimiento, curvas ROC/AUC y pruebas de auditoría con registros individuales.
"""

!pip install gdown

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.optimize import linear_sum_assignment

from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import IsolationForest

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    adjusted_rand_score,
    normalized_mutual_info_score,
    silhouette_score,
    roc_curve,
    roc_auc_score
)

# Carpeta para guardar imágenes
os.makedirs("img", exist_ok=True)

file_id = "1iLGG2XlXTMJOA31HC8C5W4NKyPyAt3BK"
url = f"https://drive.google.com/uc?id={file_id}"
output = "dataset_iot_5_variables.csv"

!gdown {url} -O {output}

df = pd.read_csv(output)

# Limpiar nombres de columnas
df.columns = df.columns.str.strip()

df.head()

print("Dimensiones del dataset:")
print(df.shape)

print("\nColumnas:")
print(df.columns)

print("\nDistribución de etiquetas:")
print(df["Etiqueta"].value_counts())

print("\nValores faltantes:")
print(df.isnull().sum())

columnas = [
    "H_L0.1_weight",
    "H_L0.1_mean",
    "H_L0.1_variance",
    "HH_jit_L0.01_mean",
    "HpHp_L0.1_radius"
]

etiquetas = sorted(df["Etiqueta"].unique())

X = df[columnas]
y_real = df["Etiqueta"]

print("Variables utilizadas:")
for col in columnas:
    print("-", col)

print("\nEtiquetas:")
print(etiquetas)

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x="Etiqueta",
    order=df["Etiqueta"].value_counts().index,
    hue="Etiqueta",
    palette="YlGnBu",
    legend=False
)

plt.title("Distribución de la variable objetivo")
plt.xlabel("Clase")
plt.ylabel("Número de registros")
plt.xticks(rotation=35, ha="right")
plt.tight_layout()

plt.savefig("img/distribucion_variable_objetivo.png", dpi=300, bbox_inches="tight")
plt.show()

def mapear_clusters_a_etiquetas(y_real, clusters):
    """
    Mapea clusters numéricos a etiquetas reales usando asignación óptima.
    K-Means no asigna nombres de clase, por eso se hace este paso.
    """
    tabla = pd.crosstab(y_real, clusters)

    cost_matrix = -tabla.values
    row_ind, col_ind = linear_sum_assignment(cost_matrix)

    mapeo = {}

    for fila, columna in zip(row_ind, col_ind):
        etiqueta = tabla.index[fila]
        cluster = tabla.columns[columna]
        mapeo[cluster] = etiqueta

    return tabla, mapeo

def calcular_metricas(y_real, y_pred):
    """
    Calcula métricas principales usando promedio ponderado.
    """
    return {
        "Exactitud": accuracy_score(y_real, y_pred),
        "Precisión": precision_score(y_real, y_pred, average="weighted", zero_division=0),
        "Sensibilidad": recall_score(y_real, y_pred, average="weighted", zero_division=0),
        "F1-score": f1_score(y_real, y_pred, average="weighted", zero_division=0)
    }

def graficar_matriz_confusion(matriz_df, titulo, archivo_salida, figsize=(10, 7)):
    """
    Genera una matriz de confusión con paleta YlGnBu.
    """
    plt.figure(figsize=figsize)

    sns.heatmap(
        matriz_df,
        annot=True,
        fmt="d",
        cmap="YlGnBu",
        linewidths=0.5,
        linecolor="white",
        cbar=True
    )

    plt.title(titulo, fontsize=14, pad=15)
    plt.xlabel("Etiqueta predicha", fontsize=12, labelpad=10)
    plt.ylabel("Etiqueta real", fontsize=12, labelpad=10)

    plt.xticks(rotation=35, ha="right")
    plt.yticks(rotation=0)

    plt.tight_layout()
    plt.savefig(archivo_salida, dpi=300, bbox_inches="tight")
    plt.show()

# Normalización para K-Means multiclase
scaler_kmeans_multi = MinMaxScaler()
X_scaled = scaler_kmeans_multi.fit_transform(X)

kmeans_multi = KMeans(
    n_clusters=5,
    init="random",
    max_iter=100,
    n_init=10,
    random_state=42
)

clusters_multi = kmeans_multi.fit_predict(X_scaled)

df_kmeans_multi = df.copy()
df_kmeans_multi["Cluster"] = clusters_multi

df_kmeans_multi.head()

tabla_multi, mapeo_multi = mapear_clusters_a_etiquetas(
    df_kmeans_multi["Etiqueta"],
    df_kmeans_multi["Cluster"]
)

print("Tabla Etiqueta vs Cluster:")
display(tabla_multi)

print("\nMapeo cluster → etiqueta:")
print(mapeo_multi)

df_kmeans_multi["Etiqueta_predicha"] = df_kmeans_multi["Cluster"].map(mapeo_multi)

matriz_confusion_multi = confusion_matrix(
    df_kmeans_multi["Etiqueta"],
    df_kmeans_multi["Etiqueta_predicha"],
    labels=etiquetas
)

matriz_confusion_multi_df = pd.DataFrame(
    matriz_confusion_multi,
    index=etiquetas,
    columns=etiquetas
)

matriz_confusion_multi_df

graficar_matriz_confusion(
    matriz_confusion_multi_df,
    "Matriz de Confusión - K-Means multiclase",
    "img/matriz_confusion_kmeans_5_variables_legible.png",
    figsize=(10, 7)
)

metricas_kmeans_multi = calcular_metricas(
    df_kmeans_multi["Etiqueta"],
    df_kmeans_multi["Etiqueta_predicha"]
)

ari_multi = adjusted_rand_score(
    df_kmeans_multi["Etiqueta"],
    df_kmeans_multi["Cluster"]
)

nmi_multi = normalized_mutual_info_score(
    df_kmeans_multi["Etiqueta"],
    df_kmeans_multi["Cluster"]
)

silhouette_multi = silhouette_score(
    X_scaled,
    df_kmeans_multi["Cluster"]
)

print("Métricas K-Means multiclase:")
for metrica, valor in metricas_kmeans_multi.items():
    print(f"{metrica}: {valor}")

print("Adjusted Rand Index:", ari_multi)
print("Normalized Mutual Information:", nmi_multi)
print("Silhouette Score:", silhouette_multi)

print("\nReporte de clasificación:")
print(classification_report(
    df_kmeans_multi["Etiqueta"],
    df_kmeans_multi["Etiqueta_predicha"],
    zero_division=0
))

centroides_multi = pd.DataFrame(
    scaler_kmeans_multi.inverse_transform(kmeans_multi.cluster_centers_),
    columns=columnas
)

centroides_multi["Cluster"] = centroides_multi.index
centroides_multi["Etiqueta_asignada"] = centroides_multi["Cluster"].map(mapeo_multi)

centroides_multi

df_binario = df.copy()

df_binario["Etiqueta_binaria"] = df_binario["Etiqueta"].apply(
    lambda x: "benign" if x == "benign" else "attack"
)

print(df_binario["Etiqueta_binaria"].value_counts())

X_bin = df_binario[columnas]
y_bin_real = df_binario["Etiqueta_binaria"]

scaler_bin = MinMaxScaler()
X_bin_scaled = scaler_bin.fit_transform(X_bin)

kmeans_bin = KMeans(
    n_clusters=2,
    init="random",
    max_iter=100,
    n_init=10,
    random_state=42
)

clusters_bin = kmeans_bin.fit_predict(X_bin_scaled)

df_binario["Cluster_binario"] = clusters_bin

df_binario.head()

tabla_binaria, mapeo_binario = mapear_clusters_a_etiquetas(
    df_binario["Etiqueta_binaria"],
    df_binario["Cluster_binario"]
)

print("Tabla binaria Etiqueta vs Cluster:")
display(tabla_binaria)

print("\nMapeo binario cluster → etiqueta:")
print(mapeo_binario)

df_binario["Etiqueta_binaria_predicha"] = df_binario["Cluster_binario"].map(mapeo_binario)

etiquetas_binarias = ["benign", "attack"]

matriz_confusion_binaria = confusion_matrix(
    df_binario["Etiqueta_binaria"],
    df_binario["Etiqueta_binaria_predicha"],
    labels=etiquetas_binarias
)

matriz_confusion_binaria_df = pd.DataFrame(
    matriz_confusion_binaria,
    index=etiquetas_binarias,
    columns=etiquetas_binarias
)

matriz_confusion_binaria_df

graficar_matriz_confusion(
    matriz_confusion_binaria_df,
    "Matriz de Confusión - K-Means binario",
    "img/matriz_confusion_kmeans_binario_legible.png",
    figsize=(7, 6)
)

metricas_kmeans_bin = calcular_metricas(
    df_binario["Etiqueta_binaria"],
    df_binario["Etiqueta_binaria_predicha"]
)

ari_bin = adjusted_rand_score(
    df_binario["Etiqueta_binaria"],
    df_binario["Cluster_binario"]
)

nmi_bin = normalized_mutual_info_score(
    df_binario["Etiqueta_binaria"],
    df_binario["Cluster_binario"]
)

silhouette_bin = silhouette_score(
    X_bin_scaled,
    df_binario["Cluster_binario"]
)

print("Métricas K-Means binario:")
for metrica, valor in metricas_kmeans_bin.items():
    print(f"{metrica}: {valor}")

print("Adjusted Rand Index:", ari_bin)
print("Normalized Mutual Information:", nmi_bin)
print("Silhouette Score:", silhouette_bin)

print("\nReporte de clasificación:")
print(classification_report(
    df_binario["Etiqueta_binaria"],
    df_binario["Etiqueta_binaria_predicha"],
    zero_division=0
))

centroides_binarios = pd.DataFrame(
    scaler_bin.inverse_transform(kmeans_bin.cluster_centers_),
    columns=columnas
)

centroides_binarios["Cluster"] = centroides_binarios.index
centroides_binarios["Etiqueta_asignada"] = centroides_binarios["Cluster"].map(mapeo_binario)

centroides_binarios

X_nb = df[columnas]
y_nb = df["Etiqueta"]

X_train, X_test, y_train, y_test = train_test_split(
    X_nb,
    y_nb,
    test_size=0.30,
    random_state=42,
    stratify=y_nb
)

scaler_nb = MinMaxScaler()

X_train_scaled = scaler_nb.fit_transform(X_train)
X_test_scaled = scaler_nb.transform(X_test)

modelo_nb = GaussianNB()
modelo_nb.fit(X_train_scaled, y_train)

y_pred_nb = modelo_nb.predict(X_test_scaled)

metricas_nb = calcular_metricas(y_test, y_pred_nb)

print("Métricas Gaussian Naive Bayes:")
for metrica, valor in metricas_nb.items():
    print(f"{metrica}: {valor}")

print("\nReporte de clasificación:")
print(classification_report(
    y_test,
    y_pred_nb,
    zero_division=0
))

matriz_confusion_nb = confusion_matrix(
    y_test,
    y_pred_nb,
    labels=etiquetas
)

matriz_confusion_nb_df = pd.DataFrame(
    matriz_confusion_nb,
    index=etiquetas,
    columns=etiquetas
)

matriz_confusion_nb_df

graficar_matriz_confusion(
    matriz_confusion_nb_df,
    "Matriz de Confusión - Gaussian Naive Bayes",
    "img/matriz_confusion_naive_bayes_legible.png",
    figsize=(10, 7)
)

X_if = df[columnas]
y_if = df["Etiqueta"]

X_train_if, X_test_if, y_train_if, y_test_if = train_test_split(
    X_if,
    y_if,
    test_size=0.30,
    random_state=42,
    stratify=y_if
)

print("Entrenamiento:", X_train_if.shape)
print("Prueba:", X_test_if.shape)
print("\nDistribución de prueba:")
print(y_test_if.value_counts())

scaler_if = MinMaxScaler()

X_train_if_scaled = scaler_if.fit_transform(X_train_if)
X_test_if_scaled = scaler_if.transform(X_test_if)

X_train_if_scaled = pd.DataFrame(X_train_if_scaled, columns=columnas)
X_test_if_scaled = pd.DataFrame(X_test_if_scaled, columns=columnas)

y_train_if = y_train_if.reset_index(drop=True)
y_test_if = y_test_if.reset_index(drop=True)

modelos_if = {}

for etiqueta in sorted(y_train_if.unique()):
    X_clase = X_train_if_scaled[y_train_if == etiqueta]

    modelo = IsolationForest(
        n_estimators=100,
        contamination=0.05,
        random_state=42
    )

    modelo.fit(X_clase)

    modelos_if[etiqueta] = modelo

print("Modelos entrenados:")
print(modelos_if.keys())

puntajes_if = pd.DataFrame(index=range(len(X_test_if_scaled)))

for etiqueta, modelo in modelos_if.items():
    puntajes_if[etiqueta] = modelo.score_samples(X_test_if_scaled)

# La clase predicha es la que obtiene mayor puntaje de normalidad
y_pred_if = puntajes_if.idxmax(axis=1)

y_pred_if.head()

metricas_if = calcular_metricas(y_test_if, y_pred_if)

print("Métricas Isolation Forest multiclase adaptado:")
for metrica, valor in metricas_if.items():
    print(f"{metrica}: {valor}")

print("\nReporte de clasificación:")
print(classification_report(
    y_test_if,
    y_pred_if,
    zero_division=0
))

matriz_confusion_if = confusion_matrix(
    y_test_if,
    y_pred_if,
    labels=etiquetas
)

matriz_confusion_if_df = pd.DataFrame(
    matriz_confusion_if,
    index=etiquetas,
    columns=etiquetas
)

matriz_confusion_if_df

graficar_matriz_confusion(
    matriz_confusion_if_df,
    "Matriz de Confusión - Isolation Forest multiclase adaptado",
    "img/matriz_confusion_isolation_forest_multiclase.png",
    figsize=(10, 7)
)

# ============================================================
# ROC/AUC para detección binaria: benign vs attack
# ============================================================

# ---------- K-Means binario ----------
y_true_kmeans_bin = df_binario["Etiqueta_binaria"].map({
    "benign": 0,
    "attack": 1
})

cluster_benign = [c for c, e in mapeo_binario.items() if e == "benign"][0]
cluster_attack = [c for c, e in mapeo_binario.items() if e == "attack"][0]

distancias = kmeans_bin.transform(X_bin_scaled)

dist_benign = distancias[:, cluster_benign]
dist_attack = distancias[:, cluster_attack]

# Mientras más alto el score, más cercano a attack que a benign
score_kmeans = dist_benign - dist_attack

fpr_kmeans, tpr_kmeans, _ = roc_curve(y_true_kmeans_bin, score_kmeans)
auc_kmeans = roc_auc_score(y_true_kmeans_bin, score_kmeans)

print("AUC K-Means binario:", auc_kmeans)


# ---------- Gaussian Naive Bayes ----------
y_true_nb_bin = y_test.apply(lambda x: 0 if x == "benign" else 1)

probas_nb = modelo_nb.predict_proba(X_test_scaled)

indice_benign = list(modelo_nb.classes_).index("benign")

# Probabilidad de ataque = 1 - probabilidad de benign
score_nb = 1 - probas_nb[:, indice_benign]

fpr_nb, tpr_nb, _ = roc_curve(y_true_nb_bin, score_nb)
auc_nb = roc_auc_score(y_true_nb_bin, score_nb)

print("AUC Gaussian Naive Bayes:", auc_nb)


# ---------- Isolation Forest ----------
y_true_if_bin = y_test_if.apply(lambda x: 0 if x == "benign" else 1)

puntajes_if_roc = pd.DataFrame(index=range(len(X_test_if_scaled)))

for etiqueta, modelo in modelos_if.items():
    puntajes_if_roc[etiqueta] = modelo.score_samples(X_test_if_scaled)

score_benign_if = puntajes_if_roc["benign"]

columnas_ataque_if = [col for col in puntajes_if_roc.columns if col != "benign"]
score_attack_if = puntajes_if_roc[columnas_ataque_if].max(axis=1)

# Mientras más alto el score, más parecido a ataque que a benign
score_if = score_attack_if - score_benign_if

fpr_if, tpr_if, _ = roc_curve(y_true_if_bin, score_if)
auc_if = roc_auc_score(y_true_if_bin, score_if)

print("AUC Isolation Forest adaptado:", auc_if)

plt.figure(figsize=(8, 6))

plt.plot(fpr_kmeans, tpr_kmeans, label=f"K-Means binario AUC = {auc_kmeans:.4f}")
plt.plot(fpr_nb, tpr_nb, label=f"Gaussian Naive Bayes AUC = {auc_nb:.4f}")
plt.plot(fpr_if, tpr_if, label=f"Isolation Forest AUC = {auc_if:.4f}")

plt.plot([0, 1], [0, 1], linestyle="--", label="Clasificador aleatorio")

plt.title("Curvas ROC - Detección binaria benign vs attack")
plt.xlabel("Tasa de falsos positivos")
plt.ylabel("Tasa de verdaderos positivos")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.savefig("img/curvas_roc_modelos.png", dpi=300, bbox_inches="tight")
plt.show()

def auditar_kmeans_binario(weight, mean, variance, jit_mean, radius):
    nuevo = pd.DataFrame({
        "H_L0.1_weight": [weight],
        "H_L0.1_mean": [mean],
        "H_L0.1_variance": [variance],
        "HH_jit_L0.01_mean": [jit_mean],
        "HpHp_L0.1_radius": [radius]
    })

    nuevo_scaled = scaler_bin.transform(nuevo)

    cluster = kmeans_bin.predict(nuevo_scaled)[0]
    etiqueta = mapeo_binario[cluster]

    print("Auditoría con K-Means binario")
    print("-----------------------------")
    print("Cluster asignado:", cluster)
    print("Resultado estimado:", etiqueta)

    if etiqueta == "attack":
        print("Interpretación: posible tráfico anómalo o ataque.")
    else:
        print("Interpretación: posible tráfico benigno.")

fila = df.iloc[2]

auditar_kmeans_binario(
    fila["H_L0.1_weight"],
    fila["H_L0.1_mean"],
    fila["H_L0.1_variance"],
    fila["HH_jit_L0.01_mean"],
    fila["HpHp_L0.1_radius"]
)

def auditar_naive_bayes(weight, mean, variance, jit_mean, radius):
    nuevo = pd.DataFrame({
        "H_L0.1_weight": [weight],
        "H_L0.1_mean": [mean],
        "H_L0.1_variance": [variance],
        "HH_jit_L0.01_mean": [jit_mean],
        "HpHp_L0.1_radius": [radius]
    })

    nuevo_scaled = scaler_nb.transform(nuevo)

    prediccion = modelo_nb.predict(nuevo_scaled)[0]
    probabilidades = modelo_nb.predict_proba(nuevo_scaled)[0]

    print("Auditoría con Gaussian Naive Bayes")
    print("----------------------------------")
    print("Etiqueta predicha:", prediccion)

    print("\nProbabilidades por clase:")
    for clase, prob in zip(modelo_nb.classes_, probabilidades):
        print(f"{clase}: {prob:.4f}")

fila = df.iloc[2]

auditar_naive_bayes(
    fila["H_L0.1_weight"],
    fila["H_L0.1_mean"],
    fila["H_L0.1_variance"],
    fila["HH_jit_L0.01_mean"],
    fila["HpHp_L0.1_radius"]
)

resumen_modelos = pd.DataFrame([
    {
        "Modelo": "K-Means multiclase",
        "Exactitud": metricas_kmeans_multi["Exactitud"],
        "Precisión": metricas_kmeans_multi["Precisión"],
        "Sensibilidad / Recall": metricas_kmeans_multi["Sensibilidad"],
        "F1-score": metricas_kmeans_multi["F1-score"],
        "AUC binario": "N/A"
    },
    {
        "Modelo": "K-Means binario",
        "Exactitud": metricas_kmeans_bin["Exactitud"],
        "Precisión": metricas_kmeans_bin["Precisión"],
        "Sensibilidad / Recall": metricas_kmeans_bin["Sensibilidad"],
        "F1-score": metricas_kmeans_bin["F1-score"],
        "AUC binario": auc_kmeans
    },
    {
        "Modelo": "Isolation Forest multiclase adaptado",
        "Exactitud": metricas_if["Exactitud"],
        "Precisión": metricas_if["Precisión"],
        "Sensibilidad / Recall": metricas_if["Sensibilidad"],
        "F1-score": metricas_if["F1-score"],
        "AUC binario": auc_if
    },
    {
        "Modelo": "Gaussian Naive Bayes",
        "Exactitud": metricas_nb["Exactitud"],
        "Precisión": metricas_nb["Precisión"],
        "Sensibilidad / Recall": metricas_nb["Sensibilidad"],
        "F1-score": metricas_nb["F1-score"],
        "AUC binario": auc_nb
    }
])

resumen_modelos

resumen_modelos.to_csv("resumen_modelos.csv", index=False)

matriz_confusion_multi_df.to_csv("matriz_confusion_kmeans_multiclase.csv")
matriz_confusion_binaria_df.to_csv("matriz_confusion_kmeans_binario.csv")
matriz_confusion_nb_df.to_csv("matriz_confusion_naive_bayes.csv")
matriz_confusion_if_df.to_csv("matriz_confusion_isolation_forest.csv")

print("Archivos generados correctamente.")